repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix]  # Automatically fix issues where possible